### ISSUE TITLE
Navigation drawer doesn't work with slide gesture

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#145]
Even from bottom

![1000114219](https://github.com/jocmp/capyreader/assets/113377431/a76a480d-6e93-49ba-a33b-c0734dc430f8)

**Comment by jocmp** [comment]
Adding to https://github.com/jocmp/capyreader/discussions/177 and closing the issue for now. There are some technical constraints that I may be able to fix in future.

**Comment by jocmp** [comment]
Now available in https://github.com/jocmp/capyreader/releases/tag/2024.07.1011
