### ISSUE TITLE
Some feeds are partially fetched

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#147]
Feed: www.latinaoggi.eu/rss.jsp?sezione=909

Different loading in Capy and Feeder.

![1000114228](https://github.com/jocmp/capyreader/assets/113377431/359efdc4-93e9-4c3b-80d2-14eace24773a)

![1000114230](https://github.com/jocmp/capyreader/assets/113377431/5174cdc8-78b1-46e8-af26-f981f83476a2)

**Comment by jocmp** [comment]
This is a result of some feeds only partially filling the article's `description` field. Ideally, the full article would be present in the feed. Full feed extraction would be better handled by a service like [Postlight Parser](https://github.com/postlight/parser) which I'm planning to investigate at some point in the future. Feel free to track that via #151
