### ISSUE TITLE
Pushing "make below as read" button makes crashing the app

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#152]
Android 14
Capy 2024.07.1003 IzzySoft
OnePlus CPH2399

![1000114244](https://github.com/jocmp/capyreader/assets/113377431/aa3f267b-1d6d-4d6c-9d5a-3adfe9a14f86)

**Comment by jocmp** [comment]
Looking into this. Can you share a few more details? For example, how many feeds do you have, and how many articles do you think there were?

**Comment by jocmp** [comment]
I was able to reproduce with the PR attached. I'll include this in the next app version, 2024.07.1005.

**Comment by jocmp** [comment]
[2024.07.1005](https://github.com/jocmp/capyreader/releases/tag/2024.07.1005) is up! Please reopen if you keep seeing the problem.
