### ISSUE TITLE
Font and Text Size Selection

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#158]
Add an option in the article view to change the relative font size. 

Additionally provide some fonts to choose from:

- System default
- Sans Serif: Open Sans? Inter?
- Serif: Vollkhorn?

**Comment by jocmp** [comment]
@serrq I think the font in your screenshot is Roboto. I believe OnePlus comes with it built-in. I updated the headline font on the article list to be bold so it should look similar now if not the same.

**Comment by ez-me** [comment]
I would recommend [Atkinson Hyperlegible](https://github.com/googlefonts/atkinson-hyperlegible/) for Sans Serif, it's easier to read, specially for people with visual impairments (without being ugly like Open Dyslexic)

**Comment by jocmp** [comment]
@ez-me Took a look at the Atkinson Hyperlegible font. Seems like a great option. I'm working on adding it to #201. Here's a sneak peek

<img src="https://github.com/user-attachments/assets/f487afae-7b54-4995-a7b1-8bc75d0de57b" width="500px">

**Comment by jocmp** [comment]
Yep! Code is ready, I'm fixing some other  things before adding it to a new
release.
