### ISSUE TITLE
Might you adding source and time in cell view?

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#161]
Screenshot taken from Feeder.

![1000114285](https://github.com/user-attachments/assets/bf712a76-60d1-457b-a2aa-28a006247e17)

**Comment by jocmp** [comment]
hey there - Source and time are on the list items/cells now. Time is relative. So a post from 1 hour ago will say "1h."

It's harder to tell the difference between the title and subtitle (source). So typography is something I can improve.

<img src="https://github.com/user-attachments/assets/26148f67-8632-4ecd-931b-03eaf2494269" width="500px" />

**Comment by jocmp** [comment]
Yep! I'm tracking card customization in #140.

**Comment by jocmp** [comment]
heads up - display options will be in the next release per https://github.com/jocmp/capyreader/pull/163 (screenshots for reference). As for the second feature request, I'm only supporting relative timestamps at this time.
