### ISSUE TITLE
OPML Importer fails on ampersand (&) characters

### ISSUE THREAD

**Issue by ConEstArthur** [jocmp/capyreader#166]
### Steps to Reproduce

It fails when you try to import an OPML.
I'm attaching a sample OPML that I have.

It works fine in other similar apps.

### Expected behavior

It imports the file successfully and show me the list of feeds.

### Screenshots or screen recording

[Sample.zip](https://github.com/user-attachments/files/16228818/Sample.zip)

### Device, Operating system, and app version

Poco x3
Android 13
Nitrogen os (aosp custom rom)

**Comment by jocmp** [comment]
@ConEstArthur thanks for providing the OPML! I'll take a look.

**Comment by jocmp** [comment]
I've identified the issue. The OPML importer is failing on the `&` in one of the feeds.

A quick fix is to edit the file. I've attached a cleaned version of it as an example: [Edited.opml.zip](https://github.com/user-attachments/files/16228991/Edited.opml.zip)

I'll also add the fix to the importer and track it via this issue. That will take a little more time.

**Comment by ConEstArthur** [comment]
> I'll also add the fix to the importer and track it via this issue. That will take a little more time.

Thanks for such a prompt response.

**Comment by jocmp** [comment]
The fix is live in the [latest release](https://github.com/jocmp/capyreader/releases/tag/2024.07.1008). Please reopen this issue if you're still seeing the problem. Thanks again for the thorough bug report.

**Comment by ConEstArthur** [comment]
> Thanks again for the thorough bug report.

May I have your email ?
I have my personal opml that fails to import.
Maybe you could look into it ?

**Comment by jocmp** [comment]
Sure thing. Feel free to reach me at support@asteriastudio.com and I'll take a look.

**Comment by jocmp** [comment]
@ConEstArthur Got your email, I see the issue. The importer is looking for an attribute with `type="rss"` to determine if an outline is a feed. I'll update the importer to look for the feed URL instead.

**Comment by jocmp** [comment]
Update is live in [2024.07.1009](https://github.com/jocmp/capyreader/releases/tag/2024.07.1009). I retested with both OPML files. Let me know if it's still causing you troubles.

**Comment by ConEstArthur** [comment]
> Let me know if it's still causing you troubles.

No errors anymore. Thanks a lot for your commendable work.

Although It fails to scrap content from a few websites as intended as of now but I believe that will get better over time as the app grows.

Thanks again ☺️
