### ISSUE TITLE
Cannot update to the latest 1008 app version

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#171]
Capy ...1008 (github)
Android 14
OnePlus CPH2399

Current Capy version
...1007 (IzzySoft)

Installer does nothing.

**Comment by jocmp** [comment]
Can you add a screenshot of what you're seeing when installing the newer version?

**Comment by jocmp** [comment]
Gotcha. This sounds like a device issue, not an app issue. Can you provide a screen recording instead?

**Comment by jocmp** [comment]
OnePlus should have a built-in screen recorder in Quick Access via the notification drawer. 

I'm guessing it's some sort of package conflict, maybe due to the source? I was able to upgrade from 1007 to 1008 on a test device without issue, but both were from GitHub.

**Comment by jocmp** [comment]
Good! I'll keep an eye on this going forward. Please reopen if you see it again.
