### ISSUE TITLE
More compact cards

### ISSUE THREAD

**Issue by serrq** [jocmp/capyreader#172]
Font size scale?

![Screenshot_2024-07-15-18-44-03-25_174643ec4e3138bdf0762d074f461918](https://github.com/user-attachments/assets/c10f319f-f219-4afd-8602-65df990fd591)

Please see the difference with Feeder.

![Screenshot_2024-07-15-18-44-37-32_56dde218d5b132d57db5f243d6cd7745](https://github.com/user-attachments/assets/eb831a7a-373b-4376-93a2-4054dc684b78)

**Comment by jocmp** [comment]
It's a good idea, I can't commit to a timeline yet. Adding this to https://github.com/jocmp/capyreader/discussions/176 for now.
