### ISSUE TITLE
App always refreshes feed at start despite "manually" is selected 

### ISSUE THREAD

**Issue by HarriBuh** [jocmp/capyreader#180]
As the title says.
I explicitly chose the manual refresh method, so the app should only catch feeds whenever I pull down the list.

App version 2024.07.1009

**Comment by jocmp** [comment]
hey @HarriBuh - let me take a look. When I added "Manually," my intention was to include "On Start" as well. I'll see what I can do to split out these two conditions.

**Comment by jocmp** [comment]
"Manually only" now skips the on-start refresh in [the latest release](https://github.com/jocmp/capyreader/releases/tag/2024.07.1010).
