### ISSUE TITLE
comicsrss.com isn't showing images

### ISSUE THREAD

**Issue by ez-me** [jocmp/capyreader#198]
### Steps to Reproduce

Steps to reproduce:

1. add https://www.comicsrss.com/rss/garfield.rss for example
2. go into any post
3. No images appear (even with full text retrieval)

### Expected behavior

An image to appear (the comic)

### Device, Operating system, and app version

Google Pixel 2 XL (taimen), Android 12L (api31), Capy Reader 2024.07.1011

**Comment by jocmp** [comment]
hey @ez-me - thanks for the detailed bug report. I found the issue. This RSS feed doesn't put the comic strip in the post's body, so the app couldn't find it. I have a fix to use the post's summary if the post body is unavailable. 

The end result is shown below. I'll push the fix up and have a new build no later than tomorrow. 

<img src="https://github.com/user-attachments/assets/691e1d45-6232-4470-b6a0-c0a141603faa" width="500px">

**Comment by jocmp** [comment]
Fixed in [2024.07.1012](https://github.com/jocmp/capyreader/releases/tag/2024.07.1012). Please reopen if you see this issue again!
