### ISSUE TITLE
App crash when opening a feed after importing

### ISSUE THREAD

**Issue by nishkaamprem** [jocmp/capyreader#202]
### Steps to Reproduce

1.open the app
2.import your subscriptions
3.tap on an imported feed

### Expected behavior

The app crashes ibstead of opening the feed and crsh of start everytime after untill you wipe the app data

**Comment by jocmp** [comment]
Does the import complete? Can you share the URL or link of feed that it crashes on?

**Comment by nishkaamprem** [comment]
Pretty much every feed after importing causes the app to crash. Im not sure this is only caused when the feeds are imported from another application

**Comment by nishkaamprem** [comment]
> Does the import complete? Can you share the feed URL that it crashes on?

Pretty much every feed after importing causes the app to crash. Im not sure this is only caused when the feeds are imported from another application

**Comment by jocmp** [comment]
I see. Can you supply a screen recording, a sample feed URL, or your OPML file? That will help me debug. Feel free to upload any of that to this thread or email it to support@asteriastudio.com if you want.

**Comment by nishkaamprem** [comment]
> I see. Can you supply a screen recording, a sample feed URL, or your OPML file? That will help me debug. Feel free to upload any of that to this thread or email it to [support@asteriastudio.com](mailto:support@asteriastudio.com) if you want.

Alright

**Comment by jocmp** [comment]
@nishkaamprem thanks for the OPML file. I tried it out and replicated the bug. One of the feeds returns relative paths like `/foo-bar` instead of `https://example.com/foo-bar` which broke the article list.

I put up a change soon to handle relative links.

**Comment by nishkaamprem** [comment]
> @nishkaamprem thanks for the OPML file. I tried it out and replicated the bug. One of the feeds returns relative paths like `/foo-bar` instead of `https://example.com/foo-bar` which broke the article list.
> 
> I put up a change soon to handle relative links.

Thanks

**Comment by jocmp** [comment]
@nishkaamprem I tested the feeds one more time. The fix is now available in version [2024.07.1013](https://github.com/jocmp/capyreader/releases/tag/2024.07.1013). Please reopen this issue if you run into the bug again. Thanks for the help!

**Comment by nishkaamprem** [comment]
Works now! Thanks

**Comment by nishkaamprem** [comment]
> @nishkaamprem I tested the feeds one more time. The fix is now available in version [2024.07.1013](https://github.com/jocmp/capyreader/releases/tag/2024.07.1013). Please reopen this issue if you run into the bug again. Thanks for the help!

Works now! Thanks

**Comment by goliv04053** [comment]
Also having this bug. @jocmp 

Also some websites when added manually makes the app crash.
Example: https://www.brasildefato.com.br/rss2.xml
