### ISSUE TITLE
Visible code in reader mode of articles 

### ISSUE THREAD

**Issue by HarriBuh** [jocmp/capyreader#205]
This started happening since the latest update to 2024.07.1012

![Screenshot_20240723-205702.png](https://github.com/user-attachments/assets/4c5a4063-c905-421b-a5a7-fa951dae976b)

![Screenshot_20240723-210208.png](https://github.com/user-attachments/assets/63bea5ef-b0e2-4383-968e-b965ec7b1a9a)

Code is being shown alongside the actual content of the article, sometimes the content of an article isn't fully shown.

**Comment by jocmp** [comment]
Hey @HarriBuh - this looks like output from the article body itself. Can you share a link to the article?

**Comment by jocmp** [comment]
Found the feed based on "tagesschau24" in the photos. It looks like this feed is passing invalid data in their video links. The same issue happens in the [NetNewsWire](https://github.com/Ranchero-Software/NetNewsWire) macOS RSS reader. I'll investigate more.

![Screenshot 2024-07-23 at 7 41 01 PM](https://github.com/user-attachments/assets/2517ad99-f2cf-4b5b-bca6-ba445e0e6834)

**Comment by jocmp** [comment]
The fix is live in the [2024.07.1014](https://github.com/jocmp/capyreader/releases/tag/2024.07.1014).

The website was doing bad things with JavaScript in the article which broke the parser. I added some custom handling to avoid this going forward. Thanks again for the bug report.
