### ISSUE TITLE
Correctly display `<author>` tag in section headers

### ISSUE THREAD

**Issue by wvffle** [jocmp/capyreader#211]
### Steps to Reproduce

1. Add factorio blog RSS: https://www.factorio.com/blog/rss
2. Go to latest blogpost
3. Scroll down and check section headings

### Expected behavior

Section headings contain author name in the `<author>` tag.
This should be rendered underneath the heading.

### Screenshots or screen recording

In that case boskid is the author

![Screenshot_20240727-134006_Capy Reader_1](https://github.com/user-attachments/assets/49da08ac-c013-4041-878e-5cca9f4fbc36)

**Comment by jocmp** [comment]
@wvffle Thanks for the feed url and the detailed bug report. I have a fix that I'll include in the next release. Here's a sneak peek of the new styling that solves for the author tag.

<img src="https://github.com/user-attachments/assets/424af0b1-dfb1-4c8c-9e56-0091b6a5247c" width="500px">

**Comment by jocmp** [comment]
Fix is in the latest release, [2024.07.1016](https://github.com/jocmp/capyreader/releases/tag/2024.07.1016). It'll be visible in full content mode.
