### ISSUE TITLE
App crashes with some RSS feed websites.

### ISSUE THREAD

**Issue by goliv04053** [jocmp/capyreader#220]
### Steps to Reproduce

1. Import OPML file
2. The file is imported partially
3. Try to add the website rss manually
4. The app crashes.

### Expected behavior

OPML import completed and the website available to read and see on the app.
I used this website as a example: https://www.brasildefato.com.br/rss2.xml

### Screenshots or screen recording

https://github.com/user-attachments/assets/eb204173-b42c-4428-b437-1c7609624051

### Device, Operating system, and app version

Lenovo Tab P11 Plus, Android 12, 2024.07.1014

**Comment by jocmp** [comment]
@goliv04053 Thanks for the video. I merged a fix for this feed that will be included in the next GitHub release.

**Comment by goliv04053** [comment]
@jocmp Thanks

**Comment by jocmp** [comment]
Fix is live in [2024.07.1017-dev](https://github.com/jocmp/capyreader/releases/tag/2024.07.1017-dev)

**Comment by goliv04053** [comment]
@jocmp Tested here and it's fully working
