### ISSUE TITLE
Can't add Microsoft Support Feeds

### ISSUE THREAD

**Issue by ez-me** [jocmp/capyreader#224]
### Steps to Reproduce

Steps to reproduce:

1. try to add for example https://support.microsoft.com/en-us/feed/rss/6ae59d69-36fc-8e4d-23dd-631d98bf74a9, or https://support.microsoft.com/en-us/feed/atom/6ae59d69-36fc-8e4d-23dd-631d98bf74a9
2. Capy Reader cannot find it

### Expected behavior

I expect the feed to appear.

### Device, Operating system, and app version

* Google Pixel 2 XL (taimen)
* Android 12L (api32)
* Capy Reader 2024.07.1016 (playstore)

**Comment by jocmp** [comment]
Thanks for the link @ez-me. I'll investigate.

**Comment by jocmp** [comment]
@ez-me I found the issue. There was some extra checking for a channel link even though these Microsoft feeds don't have one and the app doesn't need one beyond the feed URL.

This is available in version 2024.07.1019 which is headed to the Google Play Store now and should be available tomorrow. Thanks for the bug report!

**Comment by ez-me** [comment]
Thanks, it worksworks now 👍
