### ISSUE TITLE
Add support for RDF feeds

### ISSUE THREAD

**Issue by goliv04053** [jocmp/capyreader#256]
### Steps to Reproduce

1. Press Add Feed button
2. Add the link: "https://distrowatch.com/news/dww.xml"
3. Couldn't find feed

### Expected behavior

Feed be added and loaded

Also, when I put only the website it gives me some feeds to add but not all of them. 

### Screenshots or screen recording

![Screenshot_20240812-010956](https://github.com/user-attachments/assets/e1b42c3b-b6f0-41ac-909c-6a5cc30a87d6)

### Device, Operating system, and app version

Lenovo Tab P11 Plus, Android 12, 2024.08.1028-dev

**Comment by jocmp** [comment]
Thanks for the link @goliv04053. That feed isn't showing up because it's an RDF feed, not an RSS feed. The library I use to fetch feeds doesn't support RDF. I'll see if I can add it.

**Comment by jocmp** [comment]
@goliv04053 RDF support is added in the latest version, [2024.08.1034-dev](https://github.com/jocmp/capyreader/releases/tag/2024.08.1034-dev). There's some table formatting I want to add to make this distrowatch feed work with full content mode. That will be added with https://github.com/jocmp/capyreader/pull/294.

Please reopen this if you run into any issues adding this feed.
