### ISSUE TITLE
Add option to mark articles read on scroll 

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#271]
Reference

- https://github.com/jocmp/capyreader/discussions/186

**Comment by jocmp** [comment]
Closing. I investigated this and there's not a great way to do this with the way the list is currently built.

**Comment by toketin** [comment]
Hi, so it won't be a feature that could be added in this great RSS reader? Thanks for your work!

**Comment by jocmp** [comment]
@toketin I'm still planning on it, I promise! I just haven't gotten to it yet.

**Comment by jocmp** [comment]
This is available as of [2024.11.1078-dev](https://github.com/jocmp/capyreader/releases/tag/2024.11.1078-dev).
