### ISSUE TITLE
Unable to add Slashdot RSS feed

### ISSUE THREAD

**Issue by fac42** [jocmp/capyreader#276]
### Steps to Reproduce

1. Open Capy Reader application
2. Swipe to activate the left menu, press on 'Add Feed'
3. Copy the following URL [https://rss.slashdot.org/Slashdot/slashdotMain] into text box
4. Hit the 'Add' button

### Expected behavior

Expected feed to add properly, but instead get a message that feed/website is not found.

### Device, Operating system, and app version

Moto G Play 2024, Android 13, Capy Reader 2024.08.1027

**Comment by fac42** [comment]
Oh gotcha, I didn't realize there were different standards/formats for RSS feeds. I actually added Distrowatch as a feed and it seemed to worked for me, but I didn't directly use the URL for the XML file, but just the following URL [https://distrowatch.com/] and it seemed to work.

**Comment by jocmp** [comment]
@fac42 Fix is out in the latest dev release, [2024.08.1034-dev](https://github.com/jocmp/capyreader/releases/tag/2024.08.1034-dev), which should hit Google Play later this week, and F-Droid whenever that builds next if you use either of those.

Let me know if you run into any issues with this feed. Thanks again for the bug ticket.
