### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by Monirzadeh** [jocmp/capyreader#299]
### Steps to Reproduce

App currently not support RTL and shoe left to right them. Add this [feed](https://1pezeshk.com/feed)
As you see content of them get wrong direction.

### Expected behavior

Show RTL text right to left and LTR text Left to right instead of show everything LTR.

Direction should be basesd on content that app showing

**Comment by jocmp** [comment]
Thanks @Monirzadeh. You are correct that the app does not support RTL text. I'll spend some time to add it.

**Comment by jocmp** [comment]
Note to self:

- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir
- https://developer.android.com/training/basics/supporting-devices/languages

Sample feeds

- https://www.1pezeshk.com/feed
- https://www.saudiandroid.net/feed

**Comment by jocmp** [comment]
Link https://github.com/jocmp/capyreader/discussions/323

**Comment by jocmp** [comment]
This is live in [2024.09.1042-dev](https://github.com/jocmp/capyreader/releases/tag/2024.09.1042-dev). Please reopen the issue if you notice formatting issues.
