### ISSUE TITLE
All new articles in one feed show up as just now 

### ISSUE THREAD

**Issue by sozifa** [jocmp/capyreader#327]
### Steps to Reproduce

The feed https://www.tagesspiegel.de/contentexport/feed startet to show the time stamp fo all new articles as just now when refreshed - that behaviour is new and more likely related to the feed as all the others work jus fine - but maybe you can do something about it? 

### Expected behavior

When a feed is refreshed it should show the published time/date as shown under pubdate in the feed

**Comment by jocmp** [comment]
Thanks @sozifa - this is a bug with how tagesspiegel formats their September dates. I have a fix (https://github.com/jocmp/capyreader/pull/328) that I'll include in a build later today.

**Comment by jocmp** [comment]
Fix is live in [2024.09.1041](https://github.com/jocmp/capyreader/releases/tag/2024.09.1041). Please reopen this issue if you keep seeing the issue. Thanks again for the bug report!
