### ISSUE TITLE
Add FreshRSS support

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#332]
By far the [most requested](https://github.com/jocmp/capyreader/discussions/281) sync service.

Visit the [milestone](https://github.com/jocmp/capyreader/milestone/6) to track progress. 

## Reference

- FreshRSS docs https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html
- [NetNewsWire API implementation](https://github.com/Ranchero-Software/NetNewsWire/blob/445306ef2a6f9813d8cbbd876383d4b14ca8f2b7/Modules/ReaderAPI/Sources/ReaderAPI/ReaderAPICaller.swift#L57-L69)
- About Google Reader API https://feedhq.readthedocs.io/en/latest/api/index.html

**Comment by laforcem** [comment]
Will this be support for FreshRSS exclusively, or the Fever API more broadly?

**Comment by jocmp** [comment]
hey @laforcem - this will support FreshRSS by way of their Google Reader API. Once that's out I'd also like to implement Fever API as well. That will be a separate set of tickets though.
