### ISSUE TITLE
BlissOS isn't showing articles

### ISSUE THREAD

**Issue by ez-me** [jocmp/capyreader#343]
### Steps to Reproduce

1. Add https://blog.blissos.org/rss.xml
2. Wait for it to load.

### Expected behavior

Articles to show (as seen in the website)

### Device, Operating system, and app version

* Google Pixel 2 XL (taimen)
* Android 12L (api31)
* 2024.09.1041 (playstore)

**Comment by jocmp** [comment]
@ez-me Fix for this is live in 2024.09.1046 which is now live in the Play Store.
