### ISSUE TITLE
Exporting subscriptions does not work

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#344]
### Steps to Reproduce

1. Click on the export button.

What is currently happening: the android share menu open.

### Expected behavior

Open the internal android file manager to choose the location to save the export.

### Device, Operating system, and app version

Android 14.

**Comment by jocmp** [comment]
@TheOneImprove thanks for this. I updated the export button. The change will be in the next release.

**Comment by jocmp** [comment]
Fix is live in [2024.09.1044-dev](https://github.com/jocmp/capyreader/releases/tag/2024.09.1044-dev). Feel free to reopen if it's not working as expected.
