### ISSUE TITLE
can't fullscreen images in full content version

### ISSUE THREAD

**Issue by Monirzadeh** [jocmp/capyreader#352]
### Steps to Reproduce

1. Open a feed with image
2. Tap on image 
3. You see image get fullscreen
4. Tap on icon on top right to fetch full content
5. Tap on same image in full content
6. As you see image not get fullscreen anymore

### Expected behavior

See image of article in fullscreen expected to work on normal and full content mode

### Device, Operating system, and app version

Capy Reader 2024.09.1043-dev

**Comment by jocmp** [comment]
hey @Monirzadeh do you have an example feed you can link?

**Comment by jocmp** [comment]
I have a partial fix I'll ship in the next version as seen below. It works when the parser finds an image successfully, but other times the parser I use still doesn't find the lead image.

<img src="https://github.com/user-attachments/assets/5d89ebe0-84f1-4dfd-b912-e37637ca765c" width="300px">

**Comment by jocmp** [comment]
Merging this into https://github.com/jocmp/capyreader/issues/506. I have a way to fix these now.
