### ISSUE TITLE
cannot add some rss feed

### ISSUE THREAD

**Issue by etern** [jocmp/capyreader#385]
### Steps to Reproduce

1. right swipe
2. press "Add Feed"
3. paste url：http://www.aaronsw.com/2002/feeds/pgessays.rss
4. press "Add"

Couldn't find feed

- only this url failed, other url can be added
- this url can be opened from browser
- this url can be added with other RSS reader（ex: ReadYou）

### Expected behavior

Add success

**Comment by jocmp** [comment]
thanks for the report @etern. This is an issue with `http` feeds getting upgraded to `https` in the app. I have a fix that I'll ship in the next build https://github.com/jocmp/capyreader/pull/387.

**Comment by etern** [comment]
Thanks.
By the way, after update to 2024.09.1052，"Add Feed" -> "long press" does not pop up menu for paste

**Comment by etern** [comment]
Maybe I made a mistake. The paste menu works now, but not quite the same as other apps. 
Other apps will pop up menu when you press and hold for 1 second, even if you don't release your finger. This app only pops up the menu at the moment the finger is released.
Anyway, it's not a big problem, thanks

**Comment by jocmp** [comment]
The feed issue should be fixed as of 2024.09.1055. Closing for now, feel free to reopen.
