### ISSUE TITLE
Can't mark all as read offline.

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#411]
I can't mark all as read when I am offline, I don't know if this is a bug or a intended feature.

**Thank you** for your great work on this great RSS client.

**Comment by jocmp** [comment]
hey @TheOneImprove - That is definitely a bug, let me take a look to reproduce. Remind me, are you using Local feeds?

**Comment by jocmp** [comment]
I found the bug and included a fix in [2024.10.1058](https://github.com/jocmp/capyreader/releases/tag/2024.10.1058). That should hit Google Play in the next day or so if you use that source. Please reopen this if you see the problem again.
