### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by denastria** [jocmp/capyreader#417]
### Steps to Reproduce

such as the question

### Expected behavior

.

### Screenshots or screen recording

![Screenshot_20241007_194635_com android packageinstaller](https://github.com/user-attachments/assets/7d68efd2-fbe5-477a-8b95-f6127f73c259)

### Device, Operating system, and app version

Honor  9x pro, HarmonyOS 3.0.0, Capyreader 2024.10.1058

**Comment by twhite96** [comment]
Same here. Installed with F- Droid
