### ISSUE TITLE
[BUG REPORT] "Delete all" deletes favorites and preserves articles

### ISSUE THREAD

**Issue by HarriBuh** [jocmp/capyreader#433]
### Steps to Reproduce

1. Settings
2. General
3. "Delete all articles"
4. Recognise, that all favourites got deleted, unread articles of ~ 5 days stay.

### Expected behavior

What the in-app description actually says: Delete read articles, preserve favourites.

### Screenshots or screen recording

![Screenshot_20241016-195435](https://github.com/user-attachments/assets/374c376a-677a-449a-8106-ce70afe5776a)

___

![Screenshot_20241016-200237](https://github.com/user-attachments/assets/8ceb8594-2bc7-4702-8bee-f4c691ba1772)
(I had ~ 15 articles saved as favourites)

### Device, Operating system, and app version

Google Pixel 7
Android 14
Rooted with Magisk 28

**Comment by jocmp** [comment]
@HarriBuh Sorry, the text below the button is confusing. It's meant to describe the "Keep Articles" (Artikel behalten) option. The "Alle Artikel löschen" option will delete all article data including favorites.

I'm wondering if it is best to remove the clear button altogether to avoid confusion, or I can rework it to say "Clear now" and make sure it keeps favorites. Let me know what you think.
