### ISSUE TITLE
[FR] Add more options to long press action

### ISSUE THREAD

**Issue by ConEstArthur** [jocmp/capyreader#440]
### Steps to Reproduce

I think it'd be nice to have share, star options in long press menu of an article for those who do not prefer swiping gestures.

### Expected behavior

More options to existing "Mark above/below as read"

### Device, Operating system, and app version

Capy Reader - version 2024.10.1064-dev
Device - Poco x3 
Nitrogen OS A13

**Comment by jocmp** [comment]
Hey @ConEstArthur. Hope you've been well! I like the idea. I'll add star and read options to the long press menu soon.

**Comment by jocmp** [comment]
I added some more options in [2024.10.1065-dev](https://github.com/jocmp/capyreader/releases/tag/2024.10.1065-dev). Let me know what you think!

**Comment by ConEstArthur** [comment]
> I added some more options in [2024.10.1065-dev](https://github.com/jocmp/capyreader/releases/tag/2024.10.1065-dev). Let me know what you think!

Perfect implementation!
Thanks Joe, as always ☺️
