### ISSUE TITLE
Improve gesture detection

### ISSUE THREAD

**Issue by Adikso** [jocmp/capyreader#441]
Basically every time that I'm quickly scrolling through my feeds, it happens that scrolling suddenly stops, and article is being marked as read with the gesture. I'm also having this experience nearly every time I'm opening the app and starting to scroll.

Obviously it's not that it's marking as read by itself. It's caused because the way I'm scrolling is triggering the gestures (One-handed walking). However I didn't have such problems with any other app. It seems that in apps like "K-9 Mail" they have more reliable check for that. 

I had to disable the gestures, because it was too annoying

**Comment by jocmp** [comment]
Hey @Adikso. I hear you, honestly I'm glad someone else thought it was too touchy. This is Google's built-in behavior unfortunately but there are a few workarounds I can try. Stay tuned!

**Comment by Philippe-Choquette** [comment]
It's something I've noticed too

**Comment by jocmp** [comment]
A fix is live in [2024.10.1065-dev](https://github.com/jocmp/capyreader/releases/tag/2024.10.1065-dev). I opted to use a library that specifically [fixes this jank](https://issuetracker.google.com/issues/269627294). Please reopen if you keep seeing issues.
