### ISSUE TITLE
Certain UI elements cover the scrollbar when reading an article

### ISSUE THREAD

**Issue by Pixelo789** [jocmp/capyreader#460]
### Steps to Reproduce

Steps to reproduce:
1. Launch Capy Reader
2. Open an article long enough to require a scrollbar
3. Scroll

### Expected behavior

The scrollbar is bound between the top bar and the bottom gesture bar, instead of the current behavior where the top and bottom bars cover the scrollbar.

### Screenshots or screen recording

https://github.com/user-attachments/assets/0d830c29-5d57-4f00-b007-738f757784ee

### Device, Operating system, and app version

Google Pixel 3, Android 12 (latest), Capy Reader 2024.10.1066

**Comment by jocmp** [comment]
Hey @Pixelo789 - great find, and thanks for the detailed bug report. This is due to the "unpin toolbars" behavior. There's a 64px offset beneath the top bar that the scrollbar is lost under. 

This is a relatively simple thing to fix. I'll try and address it in the next week or so.

**Comment by jocmp** [comment]
This is fixed as of [2024.10.1068-dev](https://github.com/jocmp/capyreader/releases/tag/2024.10.1068-dev)
