### ISSUE TITLE
Unable to get the articles from a RSS feed

### ISSUE THREAD

**Issue by maliprinc420** [jocmp/capyreader#469]
### Steps to Reproduce

Steps to reproduce the behaviour:
1. Add the feed from <https://journal.miso.town/atom?url=https://wiki.xxiivv.com/site/now.html>
2. The feed is created but it contains no articles.

### Expected behavior

The feed should contain the articles.

### Device, Operating system, and app version

I am using the last version from F-Droid on Android 14.

**Comment by jocmp** [comment]
@shichen437 thanks for the feed link. I see the issue. None of the entries include a link but they do include an identifier. I'll add a fix to the build.

**Comment by jocmp** [comment]
This fix is live in [2024.10.1069-dev](https://github.com/jocmp/capyreader/releases/2024.10.1069-dev). F-Droid usually updates their version of Capy Reader on Wednesdays or Thursdays every week. If you want to get this fix sooner via F-Droid I'd try adding [IzzyOnDroid](https://apt.izzysoft.de/fdroid/) as a repository and the build will appear in the next day or so. There are instructions here https://f-droid.org/tutorials/add-repo/ if you are unfamiliar.

Please let me know if you run into this bug again.

<img src="https://github.com/user-attachments/assets/abb52f5b-7727-40c2-8ea1-6375ac601218" width="400px">
