### ISSUE TITLE
User-agent for fetching feed icons is generic

### ISSUE THREAD

**Issue by michaelnordmeyer** [jocmp/capyreader#496]
### Steps to Reproduce

1. Subscribe to feed
2. Monitor server log file for feed icon requests
3. Notice `okhttp/4.12.0` as the user-agent

### Expected behavior

The user-agent should be the same one used for normal feed requests, which is currently `CapyReader (RSS Reader https://capyreader.com/) okhttp/4.12.0`.

### Device, Operating system, and app version

Capy Reader 2024.11.1070

**Comment by jocmp** [comment]
Same deal as https://github.com/jocmp/capyreader/issues/495#issuecomment-2475395954, this fix is live in the latest dev build. The User-Agent should be correct going forward.

![Screenshot 2024-11-13 at 8 52 14 PM](https://github.com/user-attachments/assets/b951b5a4-4d73-46a1-8df6-8b2f5e423170)
