### ISSUE TITLE
Readd link child img handling

### ISSUE THREAD

**Issue by Bertklq1** [jocmp/capyreader#501]
### Steps to Reproduce

Click the image if any feed

### Expected behavior

Previous version we could zoom the image download it or get full preview while clicking it. Now clicking an image that is in the feed will open up the link.

Please revert it

**Comment by jocmp** [comment]
hey @Bertklq1 let me take a look. It should be an easy fix.

**Comment by jocmp** [comment]
This is fixed as of [2024.11.1075-dev](https://github.com/jocmp/capyreader/releases/tag/2024.11.1075-dev)
