### ISSUE TITLE
Missing images in full content mode

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#506]
## Background

Capy Reader uses a library called [Readability4J](https://github.com/dankito/Readability4J) that has a few rules to parse the article's full content.

Sometimes those rules fail leading to missing images in Capy's full content mode. This is an annoying issue without a single fix-all solution. Every website is different and changes over time which is part of the beauty and chaos of the web.

If you run into this issue with a feed, please post a link to the feed with an example to this thread. I'll track these to fix some point in the future. Thanks!

## Feeds

- [x] https://indianexpress.com/section/opinion/feed/
- [x] https://www.thehindu.com/opinion/feeder/default.rss
- [x] https://www.versants.com/feed/ (https://github.com/jocmp/capyreader/discussions/502#discussioncomment-11390684)
- [ ] https://www.androidauthority.com/feed/ (https://github.com/jocmp/capyreader/discussions/502#discussioncomment-11247204)
  - https://github.com/jocmp/mercury-parser/pull/16
- [x] https://www.1pezeshk.com/feed
  - https://github.com/jocmp/mercury-parser/pull/15

**Comment by PhilC813** [comment]
The articles' main image isn't shown in Capy's full content mode for the following feed:
https://mobilesyrup.com/feed/

Article example:
https://mobilesyrup.com/2024/11/28/google-releases-ai-generated-pieces-chess-game/

(I only noticed this today so maybe it used to work?)

HTML of the image:
`<img fetchpriority="high" width="1867" height="1046" src="https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess.jpg" class="attachment-full size-full wp-post-image" alt="" decoding="async" srcset="https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess.jpg 1867w, https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess-300x168.jpg 300w, https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess-1024x574.jpg 1024w, https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess-768x430.jpg 768w, https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess-1536x861.jpg 1536w, https://cdn.mobilesyrup.com/wp-content/uploads/2024/11/gen-ai-chess-417x235.jpg 417w" sizes="(max-width: 1867px) 100vw, 1867px" />`

**Comment by jocmp** [comment]
@PhilC813 an update. I'm toying around with Mercury Parser again and seeing some potential upsides. Here's a comparison of a Les Versants article. 

<table>
<tr>
<th>Before</th>
<th>After</th>
</th>
</tr>
<tr>
<td valign="top">
<img src="https://github.com/user-attachments/assets/b4e8068f-4938-4ba0-9cd4-3f56b1ccd495" width="300px">
</td>
<td valign="top">
<img src="https://github.com/user-attachments/assets/aba3b06a-5669-49b0-b75b-d3b959511186" width="300px">
</td>
</tr>
</table>

**Mobile Syrup**

<table>
<tr>
<th>Before</th>
<th>After</th>
</th>
</tr>
<tr>
<td valign="top">
<img src="https://github.com/user-attachments/assets/ec14da9d-966a-4901-b83f-b00397a784cb" width="300px">
</td>
<td valign="top">
<img src="https://github.com/user-attachments/assets/acffed14-bfd3-4366-b953-4849b61807a7" width="300px">
</td>
</tr>
</table>

**Comment by PhilC813** [comment]
Waw, seems very promising.

Do you mind checking with this article?
https://mobilesyrup.com/2024/11/28/here-are-the-2024-staples-black-friday-deals/

It's an article with Black Friday deals, and the current parser basically removes all the bullet points in which the deals are listed 😅

**Comment by jocmp** [comment]
The new parser skips over lists by default, but with a little bit of code it works: https://github.com/jocmp/capyreader/pull/569/files#diff-a5310ab57bf17835286b2a012ceca522b0f9af190ceeea2dcf80c52f82c6479dR41-R49

<img src="https://github.com/user-attachments/assets/57e2c049-1686-4921-ade7-b8d6daecd68b" width="300px">

**Comment by PhilC813** [comment]
So you can easily specify the <ul> tag as an exception, sweet. Frankly I don't really see a reason why they would be excluded by default. They are more likely to be content than ads.

Also, is there any parser which are still actively maintained? Mercury seems abandoned like Readability4J. It's not necessarily a problem, but having an active project is always a +.

**Comment by jocmp** [comment]
Couldn't agree more. I think Mercury is more extensible and maintainable between the two. I forked it and I'm working on bringing its dependencies up to date here: https://github.com/jocmp/mercury-parser.

**Comment by PhilC813** [comment]
I've updated the app to 2024.12.1080-dev and despite the reintroduction of Mercury, I'm not seeing the results you shared above with the quick check I've done with the feed "Les Versants".

https://github.com/user-attachments/assets/ec8171d1-a784-472f-9be4-8ba0d8fe5eaf

As you can see, in the same article you used for testing, the headline is still missing, and all those grey enclosures further down actually correspond to ad placements. Then there's the last ad of the page that does manage to render.

**Comment by jocmp** [comment]
Let me take another look. I may be able to filter out those ad placements too. Just to make sure I'm testing the same thing, are you using a local account?

About the sticky config, I'm able to reproduce that bug. I'll follow up with a different ticket to fix that.

**Comment by PhilC813** [comment]
> Just to make sure I'm testing the same thing, are you using a local account?

I'm using Capy with my Feedbin account.

> About the sticky config, I'm able to reproduce that bug. I'll follow up with a different ticket to fix that. #576

Don't give up!! 😆

**Comment by jocmp** [comment]
Aha, I use Feedbin's copy of Mercury Parser for those accounts. Local accounts rely on the Mercury Parser that I'm updating. So they're different right now.

I'll see what I can do to use the same version of the parser everywhere. It should result in a more consistent experience across the board.

**Comment by jocmp** [comment]
@PhilC813 I enabled the updated Mercury Parser for Feedbin accounts in [2024.12.1081-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1081-dev) and also fixed the sticky content bug. Let me know how it works for you!

**Comment by PhilC813** [comment]
Seeing some extremely positive results so far. I'm also seeing some YouTube videos that were filtered out before now being displayed properly. Solid update..!

**Comment by privacyadmin** [comment]
Possible to fix articles for this domain?

Seems like all the text and images in their articles are missing/incomplete.

Below as an example.

https://www.hardwarezone.com.sg/feature-how-spot-potential-scam-messages-ios-and-android-singapore-rcs-sms

**Comment by jocmp** [comment]
hey @privacyadmin I'll take a look. Can you open a new issue for each of those feeds using this template? https://github.com/jocmp/capyreader/issues/new?labels=full%20content%20request&template=2-full-content-request.yml 

I want to close out this mega-issue since it's hard to track
