### ISSUE TITLE
Add extra checks to the RSS checker.

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#509]
The RSS checker is not checking the following 2 checks:
- Root domain/rss.xml
- Root domain/feed.xml

Thank you for your work.

**Comment by jocmp** [comment]
@TheOneImprove those seem reasonable. I'll take a look!

**Comment by jocmp** [comment]
These new checks are available in [2024.11.1075-dev](https://github.com/jocmp/capyreader/releases/tag/2024.11.1075-dev).
