### ISSUE TITLE
[Bug]: Tap to page article interrupts scrolling

### ISSUE THREAD

**Issue by tvnmguy** [jocmp/capyreader#515]
### Steps to Reproduce

1. Go to settings
2. Go to  gestures
3. Turn on 'Tap to page article'
4. Select a article
5. Scroll from corners

### Expected behavior

Solution: Change 'Tap to scroll' positon to sides of the next article button.
![IMG_20241117_095546](https://github.com/user-attachments/assets/1932158d-61e5-424f-8593-89c9c146f6df)

### Device, Operating system, and app version

Device: Redmi note 8 pro
Android: 11, Miui 12.5
App version: 2024.11.1074-dev

**Comment by jocmp** [comment]
This is working as expected though I'll reword the setting for clarity. 

This feature is intended to work as an alternative to swipe scrolling on E Ink devices where scrolling animation can cause UI jank (https://github.com/jocmp/capyreader/discussions/497). So the idea is to use tap scrolling or gesture scrolling but not both.
