### ISSUE TITLE
code with line numbers format is hard to read

### ISSUE THREAD

**Issue by andreyorst** [jocmp/capyreader#517]
### Steps to Reproduce

1. add the https://andreyor.st/tags/emacs-lisp/feed.xml feed
2. open the [Making Emacs tabs look like in Atom](https://andreyor.st/posts/2020-05-10-making-emacs-tabs-look-like-in-atom/) post
3. scroll down to [Making Emacs tabs resize automatically](https://andreyor.st/posts/2020-05-10-making-emacs-tabs-look-like-in-atom/#making-emacs-tabs-resize-automatically)
4. observe

### Expected behavior

The line-number column is not as wide as it is currently now

### Screenshots or screen recording

![image](https://github.com/user-attachments/assets/8bab0dea-df05-4729-8302-58d17c823949)

I would expect something like

![image](https://github.com/user-attachments/assets/d8c739ae-1347-4802-93c9-654e306ee5b8)

### Device, Operating system, and app version

Samsung S23 Ultra, Android 14, Capy Reader 2024.11.1073

**Comment by jocmp** [comment]
Hey @andreyorst thanks for the in-depth details. I suspect my CSS for the table formatting evenly divides columns. Let me take a look.

**Comment by jocmp** [comment]
I have a fix (https://github.com/jocmp/capyreader/pull/523) that I'll include in the next release. Here's a demo of what it looks like

<img src="https://github.com/user-attachments/assets/e659c141-93f6-4d05-bfaa-640b8bef2bf3" width="300px">

Vertical overflow still works as expected

https://github.com/user-attachments/assets/1c792381-37b4-4dc7-8141-72e741753ab4

**Comment by andreyorst** [comment]
amazing! thanks!

**Comment by jocmp** [comment]
A fix for this is live in [2024.11.1076-dev](https://github.com/jocmp/capyreader/releases/tag/2024.11.1076-dev). I'll publish it in a Google Play release in the next day or two if you use that distribution. Please let me know if you run into any more formatting issues.
