### ISSUE TITLE
App crash when reading some feeds, highly noticed in SubStack feeds.

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#528]
### Steps to Reproduce

1. Add any substack RSS feed (ex: https://www.theshortcut.com/feed)
2. Check for new entries.
3. Open any entry.
What is currently happening: The app crash and close.

### Expected behavior

The article open to read.

### Device, Operating system, and app version

Android 14, version 2024.11.1075-dev

Note: that crash started hapenning only after the latest update.

**Comment by jocmp** [comment]
@TheOneImprove thanks for the bug report, and sorry it's crashing on you. Can you also upload your crash log here or send it to me via email at support@asteriastudio.com? That's under Settings > General > Share crash logs.

**Comment by jocmp** [comment]
No problem. @TheOneImprove I was able to crash the app on the feed after upgrading from build 1074 to 1075. I'll put up a fix today and respond here when it's live.

**Comment by jocmp** [comment]
@TheOneImprove A fix is live in [2024.11.1077](https://github.com/jocmp/capyreader/releases/tag/2024.11.1077). Feel free to reopen this issue if you keep seeing the issue.
