### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by perzarys** [jocmp/capyreader#540]
### Steps to Reproduce

- Update to version 2024.11.1075-dev
com.capyreader.app

- Open Capy Reader

-> App immediately closes, sometimes with the "Capy Reader keeps stopping" dialog box

Can provide logs later if required.

### Expected behavior

App opens

### Device, Operating system, and app version

Pixel 8, CalyxOS 6.1.0 (Android 15), Cap Reader version 2024.11.1075-dev com.capyreader.app

**Comment by jocmp** [comment]
Hey @perzarys - sorry you're running into this. I fixed an article crash bug in the latest version 2024.11.1077 that's available via [the Github Release page](https://github.com/jocmp/capyreader/releases/tag/2024.11.1077). I think F-Droid and other sources may be stuck on prior versions until they catch up. 

Can you try that version and let me know if you're still seeing the issue? If it doesn't solve your issue please send over your crash logs and I'll take a closer look.

**Comment by perzarys** [comment]
Hi @jocmp, the version you suggested fixed the issue. Thanks! Will close this.
