### ISSUE TITLE
Improve notifications summary 

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#559]
### Discussed in https://github.com/jocmp/capyreader/discussions/554

<div type='discussions-op-text'>

<sup>Originally posted by **flameshikari** November 23, 2024</sup>
I'm suggesting a feature that will notify about a number of new articles in a single notification instead a notification per article grouped by feeds.

Suggested behavior:

![image](https://github.com/user-attachments/assets/892040a9-e2ec-472a-88e0-291e4e11addd)
</div>

**Comment by Choukajohn** [comment]
I came to make this suggestion, this possibility would be great. By the way, thanks for this application!

**Comment by jocmp** [comment]
This change is live as of [2024.12.1088-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1088-dev). I wasn't able to make it exactly like the suggestion, but the elements are all there like the total count.

| Summary | Expanded view|
|--|--|
| ![Screenshot_20241229-172432](https://github.com/user-attachments/assets/8b5f5a50-ad1c-4f4c-8fc7-fee450f4ebe1) | ![Screenshot_20241229-172452](https://github.com/user-attachments/assets/f6ea795f-bf6c-4585-94a0-353e42212891) |
