### ISSUE TITLE
Scroll position is shared between feeds

### ISSUE THREAD

**Issue by PhilC813** [jocmp/capyreader#561]
### Steps to Reproduce

1. Identify two feeds with a sufficient number of articles to fill past the screen
2. Open the articles list for the first feed, and scroll somewhere down the list
3. Switch to the other feed; the scroll position will be the same as in the previous feed

### Expected behavior

Two possible intuitive implementations for the user:
- Each feed has an individually-saved scroll position, which isn't based on the previous one
- The scroll position is reset every time you switch feeds

### Screenshots or screen recording

The following screen recording uses "Unread" feeds sorted with oldest articles first as example, but the same occurs in the "All" feeds section.

https://github.com/user-attachments/assets/28c60f57-f0ec-41b4-ae05-3f34ec5f76b5

### Device, Operating system, and app version

REDMAGIC 9 Pro, Android 14, Capy Reader 2024.11.1078-dev (latest from GitHub)

**Comment by jocmp** [comment]
Thanks @Philippe-Choquette. This has been a bug since Capy started. It's caused by the fact that, behind the scenes, the list is shared between all pages and the filter changes between each.

I remember running into issues trying to solve it several months ago, but I want to fix it since it is very unexpected.

**Comment by jstride** [comment]
Hi @jocmp - the latest update is much better now. On unread though it jumps the feed around when you have 'mark as read on scroll' enabled. I would have expected it not to change what's on screen when I've paused scrolling.

**Comment by jstride** [comment]
https://github.com/user-attachments/assets/656c61de-a3bd-412a-b133-b72cc8a5758a

**Comment by jocmp** [comment]
@jstride sorry for that. I pulled the latest release and I'll push up a fix asap, hopefully tomorrow.

**Comment by jocmp** [comment]
A fix is live in [2024.12.1080-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1080-dev) for the unread mark-as-read bug. This retains the initial fix for reseting the scroll position. @jstride or @PhilC813 feel free to reopen this or start a new issue if you see anything wrong. Thanks!
