### ISSUE TITLE
Fetch read articles

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#564]
### Discussed in https://github.com/jocmp/capyreader/discussions/533

<div type='discussions-op-text'>

<sup>Originally posted by **Alkarex** November 20, 2024</sup>
With the GReader API, it is possible to fetch articles that are read and/or unread.
While fetching unread articles is the most common use-case, it can sometimes be relevant to be able to fetch read articles as well.
Indeed, some articles might have been read from the Web interface or from another device or app.

So when the interface is set to show *All articles*, a "pull to refresh" should also fetch read articles from the server.
Or at least when the user is in a given feed or category, to selectively retrieve read articles from that feed or category.

Related to:
* https://github.com/jocmp/capyreader/discussions/532

I can give more details if this is not clear enough, and do not hesitate to ask for help on back-end side (FreshRSS).
</div>

**Comment by Alkarex** [comment]
See https://github.com/jocmp/capyreader/discussions/532#discussioncomment-11457886

It looks like *read* articles are fetched. Nice 👍🏻 
However they seem to be fetched also when in *Show unread* view, which seems a bit overkill.

**Comment by jocmp** [comment]
As mentioned in https://github.com/jocmp/capyreader/discussions/532#discussioncomment-11465531, I'll look into making the refresh more intelligent via #575.
