### ISSUE TITLE
The Reader does not accept refreshing manually

### ISSUE THREAD

**Issue by TheOneImprove** [jocmp/capyreader#580]
### Steps to Reproduce

1. Change "Refresh Feeds" settings to any option.
2. Change the settings to "Manually only".

What is happening: the reader does not accept that option and always revert to the last chosen option before switching to manual refresh.

This bug has been happening for very long time.

### Expected behavior

The player does not auto refresh and only refresh manually.

### Device, Operating system, and app version

Version: 2024.12.100-dev

**Comment by jocmp** [comment]
@TheOneImprove I wasn't able to reproduce this. Does this happen to any other setting or just the "Refresh Feeds" one?
