### ISSUE TITLE
Failed to parse auth on FreshRSS login

### ISSUE THREAD

**Issue by vk2r** [jocmp/capyreader#581]
### Steps to Reproduce

I tried to log in with my instance with a public domain url and I got the following problem: “Failed to parse auth”.

My domain is the following: “https://rss.vk-studios.net”.
My password includes the following characters: “?¿”

### Expected behavior

I hope it logs in correctly to my FreshRSS instance.

### Device, Operating system, and app version

Android in FDroid Store - 2024.12.1080-DEV

**Comment by jocmp** [comment]
hey @vk2r that "Failed to parse auth" error occurs when the login response comes back but isn't formatted correctly, so I don't think it's should be a problem `?` characters.

In a terminal, can you try the following command out? Replacing `alice` with your username and `Abcdef123456` with your password

```sh
curl 'https://rss.vk-studios.net/api/greader.php/accounts/ClientLogin?Email=alice&Passwd=Abcdef123456'
```

I would expect output like the following. Can you let me know what the response includes? Please obfuscate anything after the `=`.

```
SID=alice/8e6845e089457af25303abc6f53356eb60bdb5f8
Auth=alice/8e6845e089457af25303abc6f53356eb60bdb5f8
```

**Comment by vk2r** [comment]
Sorry for the delay. Unfortunately I have not been able to log in. I get the following error message “Unauthorized!”. My credentials are correct.  I was wondering if it would be better to log in with this option (insecure according to the documentation) ...

![imagen](https://github.com/user-attachments/assets/8e9f5d51-a5fe-431e-96b0-19bfcbfe42de)

**Comment by jocmp** [comment]
no problem. Thanks for trying out that command. The "Unauthorized!" does explain parse error.

Just to confirm, when you log in, are you using the API password under the API Management section in your settings? This will probably be located at https://rss.vk-studios.net/i/?c=user&a=profile for you. ([FreshRSS docs](https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html#enable-the-api-in-freshrss))

You shouldn't need the "Allow unsafe..." setting. Here's how I've set up my instance as an example for the "Authorization" section. The only option I have enabled is "Allow API access."

![Screenshot 2024-12-07 at 9 30 32 PM](https://github.com/user-attachments/assets/ebcdd4b6-414f-4ac8-b36e-52b52936582d)

**Comment by vk2r** [comment]
I am not using the API password. I am only using the web-form login password.

**Comment by jocmp** [comment]
Gotcha. You'll need to enter the API Password into the password field on Capy. In my testing the FreshRSS doesn't accept the web login password.

**Comment by vk2r** [comment]
I have not been able to log in correctly either. Neither with my nick, email nor the same password (I put the same one for the Mobile API). I have also updated to the latest version that includes the URL with “/api/greader.php” and I have not been able to log in either.

**Comment by jocmp** [comment]
Going back to the `curl` result, this may be a problem between any client and FreshRSS. Have you been able to get the API to work on other apps? Depending on your hosting situation there may be a problem like https://github.com/FreshRSS/FreshRSS/discussions/6715.

**Comment by vk2r** [comment]
I have tried the URL you mentioned a few moments ago with curl and now it gives me a code 200. I have updated my API password and that URL works correctly, however, in the APP I still can't log in correctly.

**Comment by vk2r** [comment]
I have successfully logged into the application. The problem is that the application asks for the email instead of the nickname. I recommend you to improve the login form, requesting only the domain (adding below the “https://” next to “/api/greader.php”) and instead of asking for the email, change it to nickname.

**Comment by jocmp** [comment]
Glad to hear, and thanks for your patience. I added your suggestions to https://github.com/jocmp/capyreader/issues/588 and I'll make sure to add them to the next release.

**Comment by soumyaDghosh** [comment]
Hii, I am still facing this error. I am using `news.decent.im` and I entered my username and password, but it's still the same. I am getting Failed with status 404 in the app. I used the same creds and logged in NewsFlash and in other clients though.

**Comment by jocmp** [comment]
@soumyaDghosh 404 sounds like the wrong endpoint. Did you enter in `https://news.decent.im/api/greader.php` for the server? The whole URL is required.

**Comment by soumyaDghosh** [comment]
Thanks! I am a fool! It works now.

**Comment by rrrevin** [comment]
> I have successfully logged into the application. The problem is that the application asks for the email instead of the nickname. I recommend you to improve the login form, requesting only the domain (adding below the “https://” next to “/api/greader.php”) and instead of asking for the email, change it to nickname.

This fixed it for me as well. Thanks! Definitely need to have the logon form updated to state this.
