### ISSUE TITLE
Improve tablet layout

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#583]
Combine article and feed list

- https://github.com/jocmp/capyreader/discussions/499#discussioncomment-11491675

**Comment by jocmp** [comment]
Combined list feeds are done as of [2024.12.1088-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1088-dev).

**Comment by keithnet** [comment]
Could this be an option in portrait mode on a tablet too?
