### ISSUE TITLE
Unable to link FreshRSS instance when OIDC login used

### ISSUE THREAD

**Issue by UncleArya** [jocmp/capyreader#587]
### Steps to Reproduce

1. Open Capy Reader
2. Tap on 'FreshRSS'
3. Enter Server, Email, Password
4. Tap 'Log in'
5. Receive 404 error

### Expected behavior

Log in and access self-hosted FreshRSS feed. I have tried both the login credentials for my FreshRSS account and for my OIDC login via Authentik. I have been able to login to other apps that support FreshRSS without issue, which leads me to believe it is an issue with Capy Reader missing the OIDC step and hopefully not me being a complete dummy.

### Device, Operating system, and app version

Google Pixel 7, Android 15

**Comment by jocmp** [comment]
Hey @UncleArya you're right, Capy Reader doesn't account for OAuth or OIDC. It only uses the [API password](https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html) for FreshRSS that's configured separately from the main account password. That said, what other apps are you using that support OIDC? I can take a look and compare.

**Comment by UncleArya** [comment]
Hello! I have been testing out the recommended android clients listed on the FreshRSS page since I set up my feeds last week. I am able to log into Readrops and Read You without issue. The only difference I noticed logging into my FreshRSS instance on their apps was that they asked for my Username instead of an email like Capy Reader does. Not sure if that is helpful information or not.

**Comment by jocmp** [comment]
Definitely useful. Another user ran into similar UI issues in #581 that I'll remedy with #588.

I double checked Readrop's implementation and it looks exactly like Capy's. Neither explicitly require knowledge about OAuth. Just want to confirm a few things:

- Your FreshRSS username should go in the email field
- The fully qualified API URL should go in the Server field, e.g. `https://example.com/api/greader.php`. This is slightly different than Readrops too.

Lastly, does the following command work for you via a command line? Replacing example.com with your domain, `alice` with your username, and `Abcdef123456` with the password you use.

```
curl 'https://example.com/api/greader.php/accounts/ClientLogin?Email=alice&Passwd=Abcdef123456'
```

The output should look like the following codeblock. The `Auth` variable is essentially all Capy needs to work.

```
SID=alice/8e6845e089457af25303abc6f53356eb60bdb5f8
Auth=alice/8e6845e089457af25303abc6f53356eb60bdb5f8
```

**Comment by UncleArya** [comment]
Thanks for looking into it and providing those instructions. I am able to login and start using Capy Reader! It turns out it was indeed user error. I had been using https://example.com/api/ without the greader.php at the end. I see that full URL is shown in the text field in grey before you start typing in it, so I missed that. I apologize. The login did indeed work with just the username so perhaps a suggestion would be to edit the field title from 'Email' to 'Username' when linking FreshRSS? I had also been attempting to login with my account email instead of a username, so I really had no chance at ever logging in haha. I appreciate you taking the time to help me out. Capy Reader is definitely my favourite of the FressRSS compatible apps and will be my daily driver now going forward 😊

**Comment by jocmp** [comment]
Good to hear. No need to apologize, I'm sorry for the confusing inputs. I have a draft to swap in "Username" that I'll include in an upcoming release (#591). Thanks for trying out the app!
