### ISSUE TITLE
Add opt-in setting for moving to next feed on read

### ISSUE THREAD

**Issue by sozifa** [jocmp/capyreader#597]
### Steps to Reproduce

Click all read butzon
Side drawer opens 

### Expected behavior

Just mark all as read - open nothing

**Comment by jocmp** [comment]
hey @sozifa - this is a new feature i'm testing out. I'll add a setting to disable it in the next release and make it opt-in only. I'll respond here when that's ready.

**Comment by jocmp** [comment]
Fixed in version the latest version, 2024.12.1083.
