### ISSUE TITLE
Support self-signed certificates

### ISSUE THREAD

**Issue by paulv** [jocmp/capyreader#628]
### Steps to Reproduce

1. Add a FreshRSS account
2. Enter a URL with a self signed certificate
3. Tap log in
4. See the error included below

### Expected behavior

I should be able to log in.

I created a custom CA and added it to the list of trusted CA certificates, but that didn't fix the issue. If I visit the FreshRSS site in chrome, I do not get any TLS errors.

### Screenshots or screen recording

![Screenshot_20241224-181901](https://github.com/user-attachments/assets/25c814d3-1c00-47a8-9759-bab68ebed799)

### Device, Operating system, and app version

Google Pixel 7, Android 15, Capy Reader version 2024.12.1086.

**Comment by jocmp** [comment]
Hey @paulv - self-signed certs are disabled by default by Android for apps. I'll see if I can add them as an option via the network config.

**Comment by jocmp** [comment]
This should be available as of [2024.12.1087](https://github.com/jocmp/capyreader/releases/tag/2024.12.1087). Feel free to reopen if certs still aren't working.
