### ISSUE TITLE
FreshRSS: Favicons are not displayed

### ISSUE THREAD

**Issue by OrkoGrayskull** [jocmp/capyreader#629]
### Steps to Reproduce

Hello,

I am using version 2024.12.1086 in combination with FreshRSS. In FreshRSS all favicons of the feeds are displayed. In Capy Reader, however, the favicon is not displayed for any feed.

### Expected behavior

Display of the favicons that are stored in FreshRSS.

### Device, Operating system, and app version

Google Pixel 8. GrapheneOS. Capy Reader 2024.12.1086.

**Comment by jocmp** [comment]
@OrkoGrayskull do the favicons appear as blank icons or do they appear as a generic RSS icon? The former points to URLs that exist but aren't loading correctly. The fallback RSS icon appears when the subscription iconUrl is completely missing on the FreshRSS API. Any screenshots may help too.

**Comment by OrkoGrayskull** [comment]
I'm sorry. That was my mistake. The nginx configuration was too strict.

**Comment by jocmp** [comment]
No problem. Glad it's working now!

**Comment by srasmus** [comment]
> I'm sorry. That was my mistake. The nginx configuration was too strict.

I seem to be running into the same problem. I'd be curious to know what it was that fixed it. I've messed around with my ngnix configuration to no avail.
