### ISSUE TITLE
Can't refresh feeds on FreshRSS

### ISSUE THREAD

**Issue by ltnzr** [jocmp/capyreader#630]
Version: 2024.12.1083 (from F-Droid)

I have a successfully linked FreshRSS account, articles fetched via FreshRSS are shown, read/unread/favorites status are synced as they should, but it's impossible to refresh the feeds from Capy Reader, neither manually nor on startup nor every 15 minutes, for instance.
Nothing updates, but there are new posts on my feeds, if I refresh from the web interface of FreshRSS, I can see them.
Not sure what to do to try to debug further.
Thanks in advance for your help.

**Comment by jocmp** [comment]
Hey @ltnzr just a few questions to help debug. When you say statuses are synced but nothing updates, did articles sync successfully the first time? Can you post screenshots comparing the web to what you see in the app? That will also be helpful. Lastly, if you're coming from a different app, does your instance sync successfully to that?

**Comment by ltnzr** [comment]
Hi,
No, I could not sync the first time. At first I thought I did not link the account successfully, but when I refreshed from FreshRSS I could see them also in Capy. I do not have another client to test, sorry.
I'm not sure how to help sending screenshots. I do see the same articles (although not in the same order, don't know if that's normal) when I refresh from FreshRSS, so syncing in that direction works. And reading one on Capy updates the read status as it should, it is marked read on FreshRSS.
There is just nothing happening when I try to refresh from Capy.

**Comment by ltnzr** [comment]
Update: I tried the notifications and that seems to work! So I do receive notifications that new articles are available, but don't see them in the feeds list in the unread view (nor in the All view). Very strange.

**Comment by jocmp** [comment]
Hey I'm glad something is working for you! That means the article sync works at least. You could try logging out via Settings and logging back in to see if it's a transient issue, but other that I'm not sure why they don't appear in the UI.

**Comment by ltnzr** [comment]
As a matter of fact, almost everything is working, thanks!
Just the command to refresh the feeds does not seem to work when sent from the app. If I trigger the refresh from the web UI, everything is OK after that.

**Comment by jocmp** [comment]
Great! You're right, the refresh command will only fetch articles that are available on the web. The refresh functionality only pulls articles that the web has already fetched. I believe there's a way to set up automatic refresh on the server so that Capy can pull the latest articles: https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html

**Comment by ltnzr** [comment]
OK, I finally understand it more, sorry!
This said, it would be nice if this was possible, as I only want to refresh manually when I check my feeds on the app or web UI. I'll stick to the web UI for the time being, then. But thanks for the work on the app.
Feel free to close this issue if you consider it normal behaviour.

**Comment by jocmp** [comment]
Yeah, unfortunately there's no way to trigger a server refresh in addition to the app sync from the app. I'll definitely address this if that changes in the future. Thanks for trying out the app!

**Comment by qfa-ok** [comment]
Hi there! Is this helpful for that?
https://freshrss.github.io/FreshRSS/en/users/09_refreshing_feeds.html#online-cron

**Comment by ltnzr** [comment]
Thanks, but no, I would like to be able to trigger this only when I want.
Like I do on the FreshRss interface, just when I open it from time to time.
Maybe the use case is a bit stupid and no one else does it like that. This is just me thinking refreshing it when I'm not looking is useless...

**Comment by qfa-ok** [comment]
Sure, me too!
I was thinking on implementing that request in the app button.
but I ~~read~~ realized that it doesn't work that way.
I don't have idea but the button in the web UI calls href="./?c=feed&a=actualize". Is this useless either? (for devs)

**Comment by jocmp** [comment]
Hey @qfa-ok - thanks for helping troubleshoot. For general reference, the cron approach is the recommended way to go. It might be possible to implement an approach to call the `/actualize` endpoint based on the docs you shared but I think that cron covers most cases for most users.
