### ISSUE TITLE
Feed Favicons are white boxes

### ISSUE THREAD

**Issue by danielkillam** [jocmp/capyreader#636]
### Steps to Reproduce

Using FreshRSS to sync feeds, favicons for all feeds are showing as white boxes. Tried logging out and logging back in but still seems to be happening 

### Expected behavior

Would like to sync favicons from all subscribed feeds

### Device, Operating system, and app version

Samsung Galaxy Tab S8, Galaxy S24 Ultra

**Comment by danielkillam** [comment]
Sorry forgot to attach a screenshot to demonstrate
![SmartSelect_20241227_091315_Capy Reader](https://github.com/user-attachments/assets/02d10064-1714-4a7c-b542-68b30c0215af)

**Comment by jocmp** [comment]
Hey @danielkillam this sounds like a similar issue to one reported yesterday (https://github.com/jocmp/capyreader/issues/629#issuecomment-2562944411). This may be a network configuration issue or potentially an app auth issue.

Are you able to retrieve any of those favicons via the command line or in an unauthenticated browser request? For instance, you can grab a favicon URL from the web UI and request it. It may be returning a non-200 HTTP status.

```sh
curl -v https://demo.freshrss.org/f.php?f2b1439b --output /dev/null
```

output

```
# ...
* Request completely sent off
< HTTP/2 200
< server: nginx/1.22.1
< date: Fri, 27 Dec 2024 21:11:52 GMT
< content-type: image/vnd.microsoft.icon
< cache-control: public, max-age=1382400
< last-modified: Tue, 24 Dec 2024 19:00:02 GMT
< etag: "1d81b195bb8cb949ddfd1a7560e20067"
< content-disposition: inline; filename="f2b1439b.ico"
< strict-transport-security: max-age=63072000
<
{ [318 bytes data]
```

![freshrss demo](https://github.com/user-attachments/assets/c8995e0d-8ed4-4f6d-ad92-fe94f7845386)

**Comment by danielkillam** [comment]
Just tested the curl command in termux, looks like it went through

Also, oddly I noticed Capy on my phone picks up some of the favicons, but not all of them (see screenshot)

Curl output below

--output /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Host demo.freshrss.org:443 was resolved.
* IPv6: 2001:41d0:302:2000::70a
* IPv4: 51.254.207.230[https://51.254.207.230]
*   Trying 51.254.207.230:443...
*   Trying [2001:41d0:302:2000::70a]:443...
* Immediate connect fail for 2001:41d0:302:2000::70a: Network is unreachable
* Connected to demo.freshrss.org[https://demo.freshrss.org] (51.254.207.230[https://51.254.207.230]) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /data/data/com.termux/files/usr/etc/tls/cert.pem
*  CApath: /data/data/com.termux/files/usr/etc/tls/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [106 bytes data]
* TLSv1.2 (IN), TLS handshake, Certificate (11):
{ [2638 bytes data]
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
{ [300 bytes data]
* TLSv1.2 (IN), TLS handshake, Server finished (14):
{ [4 bytes data]
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
} [37 bytes data]
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.2 (OUT), TLS handshake, Finished (20):
} [16 bytes data]
* TLSv1.2 (IN), TLS handshake, Finished (20):
{ [16 bytes data]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384 / x25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=freshrss.org[https://freshrss.org]
*  start date: Nov  8 01:03:56 2024 GMT
*  expire date: Feb  6 01:03:55 2025 GMT
*  subjectAltName: host "demo.freshrss.org[https://demo.freshrss.org]" matched cert's "demo.freshrss.org[https://demo.freshrss.org]"
*  issuer: C=US; O=Let's Encrypt; CN=R10
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
{ [5 bytes data]
* using HTTP/2
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0* [HTTP/2] [1] OPENED stream for https://demo.freshrss.org/f.php?f2b1439b
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: demo.freshrss.org[https://demo.freshrss.org]]
* [HTTP/2] [1] [:path: /f.php?f2b1439b]
* [HTTP/2] [1] [user-agent: curl/8.8.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /f.php?f2b1439b HTTP/2
> Host: demo.freshrss.org[https://demo.freshrss.org]
> User-Agent: curl/8.8.0
> Accept: */*
>
* Request completely sent off
{ [5 bytes data]
< HTTP/2 200
< server: nginx/1.22.1
< date: Fri, 27 Dec 2024 21:37:17 GMT
< content-type: image/vnd.microsoft[https://vnd.microsoft].icon
< cache-control: public, max-age=1641600
< last-modified: Tue, 24 Dec 2024 19:00:02 GMT
< etag: "1d81b195bb8cb949ddfd1a7560e20067"
< content-disposition: inline; filename="f2b1439b.ico"
< strict-transport-security: max-age=63072000
<
{ [318 bytes data]
100   318    0   318    0     0    265      0 --:--:--  0:00:01 --:--:--   265
* Connection #0 to host demo.freshrss.org[https://demo.freshrss.org] left intact
~ $ curl -v https://demo.freshrss.org/f.php?f2b1439b --output
Dan Killam
Pronouns: He/him
Environmental Scientist
San Francisco Estuary Institute
https://dantheclamman.blog

Dec 27, 2024 1:14:09 PM Josiah Campbell ***@***.***>:

**Comment by jocmp** [comment]
I just pushed a new version of the app, [2024.12.1087](https://github.com/jocmp/capyreader/releases/tag/2024.12.1087), that will log any favicon errors. These can be exported via Settings > General > "Share crash logs" under the Advanced section. That file should contain something that looks like the log below.

If you update to that version, can you paste those partial logs here or shoot the entire log file to me at support@asteriastudio.com? I can investigate more from there. Thanks for bearing with me!

```
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: handled_exception
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: coil.network.HttpException: HTTP 404: 
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at coil.fetch.HttpUriFetcher.executeNetworkRequest(HttpUriFetcher.kt:228)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at coil.fetch.HttpUriFetcher.access$executeNetworkRequest(HttpUriFetcher.kt:31)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at coil.fetch.HttpUriFetcher$executeNetworkRequest$1.invokeSuspend(Unknown Source:15)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
12-27 17:01:08.724 21888 21888 E cr.favicon_badge: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
```

**Comment by danielkillam** [comment]
I just got back home from traveling and discovered favicons do get loaded over local network. I disconnect and they stop loading. Then I connect via VPN and they start again! So I do think it's something related to my nginx config, I will fiddle with it! Sorry for false alarm!

**Comment by jocmp** [comment]
Hey good to hear there's a pattern! No need to apologize. Feel free to reopen this issue if needed.
