### ISSUE TITLE
Cyrillic issue

### ISSUE THREAD

**Issue by Sergo1217** [jocmp/capyreader#640]
### Steps to Reproduce

Feeds with Cyrillic are displayed incorrectly

### Expected behavior

Screenshot below
![Screenshot_20241228_024346](https://github.com/user-attachments/assets/a89e7aff-d0b1-4649-b011-c61b312a3a67)

### Screenshots or screen recording

![Screenshot_20241228_023747](https://github.com/user-attachments/assets/ed132ea0-b781-4b9c-8920-18f4f2ea3065)

### Device, Operating system, and app version

Any

**Comment by Sergo1217** [comment]
feed https://4pda.to/feed

**Comment by jocmp** [comment]
Thanks for the details @Sergo1217, and sorry that you ran into this. I have [a fix](https://github.com/jocmp/capyreader/pull/641) that I'll publish in the next release.

<img src="https://github.com/user-attachments/assets/b9eaa60b-8059-41f6-9025-4de482b0eea3" width="300px">

**Comment by jocmp** [comment]
The fix is available with [2024.12.1088-dev](https://github.com/jocmp/capyreader/releases/tag/2024.12.1088-dev). Please reopen this issue if you keep seeing this bug!
