### ISSUE TITLE
Local search

### ISSUE THREAD

**Issue by jocmp** [jocmp/capyreader#91]
Reference

- https://github.com/gvsucis/art-at-gvsu-android/blob/f2ca68cddda7dc2a8aa285929face4a0c9d61712/app/src/main/java/edu/gvsu/art/gallery/ui/SearchIndexSearchBar.kt#L25-L39

https://github.com/jocmp/capyreader/discussions/296

**Comment by rudolfmu** [comment]
I would also like to have a search. For me searching all titles would do. I read many feeds, and being able to search the titles for keywords would be of help. I still use 
https://f-droid.org/packages/ru.yanus171.feedexfork/
in parallel as this is the only one I know of with a search feature.
Thank you for giving us your good app!

**Comment by jocmp** [comment]
@rudolfmu thanks for trying out the app. I'm still planning on article search either after I complete #199 or #196. That makes sense to search titles. I also want search to look at article summaries when they're available.

**Comment by rudolfmu** [comment]
My main point is searching titles. I read about something two days ago and need to reread it. I have hundreds a day, so visual search is cumbersome.
If I need a more global search I can also use my favorite web search.
So if it is easier to just implement a title search, that would do. If it makes little difference, a complete search would also be fine.

**Comment by jocmp** [comment]
Local search is available as of [2024.08.1036-dev](https://github.com/jocmp/capyreader/releases/tag/2024.08.1036-dev). The feature will search exact text matches in the article's title or summary within the current drawer section. If you search in "All," your search will match against all articles. Changing to "Unread" will only search unread articles, and changing to a tag or feed will only search within that selection.

**Comment by rudolfmu** [comment]
Thank you very much!
